import { resolvePatternsForPlan, type Plan } from './composer';
import type { OutputFile } from '@/lib/patterns/types';

function slugifyName(input: string): string {
  return (
    input
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'tweakmizu-project'
  );
}

function renderPackageJson(plan: Plan): OutputFile {
  const pkg = {
    name: slugifyName(plan.intent.productName),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@aspect/commerce': '^0.1.0',
      '@aspect/css': '^0.1.0',
      '@aspect/finance': '^0.1.0',
      '@aspect/react': '^0.1.0',
      '@aspect/tokens': '^0.1.0',
      'lucide-react': '^0.488.0',
      next: '^15.4.10',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      '@tailwindcss/postcss': '^4.0.0',
      '@types/node': '^20.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      tailwindcss: '^4.0.0',
      typescript: '^5.0.0',
    },
  };
  return {
    path: 'package.json',
    contents: JSON.stringify(pkg, null, 2) + '\n',
  };
}

function renderReadme(plan: Plan): OutputFile {
  const lines = [
    `# ${plan.intent.productName}`,
    '',
    plan.intent.description,
    '',
    `Generated by **tweakmizu** — industry: \`${plan.intent.industry}\`, stack: \`${plan.intent.stack}\`, tone: \`${plan.intent.tone}\`, density: \`${plan.intent.density}\`.`,
    '',
    '## Pages',
    '',
    ...plan.entries.map((entry) => `- \`${entry.route}\` — ${entry.title} (${entry.patternId})`),
    '',
    '## Getting started',
    '',
    '```bash',
    'pnpm install',
    'pnpm dev',
    '```',
    '',
    'Open http://localhost:3000 to view the site.',
    '',
    '## Tweakmizu substrate',
    '',
    'This project ships with a `.tweakmizu/substrate.json` file describing its design system:',
    'tokens, layout primitives, allowed component variants, and pattern ids. Point your AI',
    'coding tool (Cursor, Claude Code, v0, bolt) at it so subsequent edits inherit the grammar.',
    '',
    `Rationale at generation time: ${plan.rationale}`,
    '',
  ];
  return { path: 'README.md', contents: lines.join('\n') };
}

function renderSubstrate(plan: Plan): OutputFile {
  const substrate = {
    $schema: 'https://tweakmizu.dev/schema/substrate-v1.json',
    substrateVersion: 1,
    project: {
      name: plan.intent.productName,
      industry: plan.intent.industry,
      stack: plan.intent.stack,
      tone: plan.intent.tone,
      density: plan.intent.density,
      generatedAt: plan.createdAt,
      tweakmizuVersion: '0.1.0',
    },
    patterns: plan.entries.map((entry) => ({
      id: entry.patternId,
      route: entry.route,
      title: entry.title,
    })),
    primitives: {
      available: ['Stack', 'Inline', 'Cluster', 'Grid', 'Center', 'Sidebar', 'Split', 'Cover'],
      importPath: '@aspect/react',
    },
    rules: [
      'Use layout primitives (Stack, Inline, Cluster, Grid) instead of manual flex/grid CSS',
      'Use semantic color tokens (surface, text, border, action, feedback)',
      'Do not hardcode pixel values for padding, margin, or gap — use the spacing scale',
      'Prefer mizu components over raw HTML when one exists (Button not <button>)',
      'Import industry-specific components from @aspect/commerce or @aspect/finance when available',
    ],
  };
  return {
    path: '.tweakmizu/substrate.json',
    contents: JSON.stringify(substrate, null, 2) + '\n',
  };
}

function renderTsconfig(): OutputFile {
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  };
  return {
    path: 'tsconfig.json',
    contents: JSON.stringify(tsconfig, null, 2) + '\n',
  };
}

function renderNextConfig(): OutputFile {
  return {
    path: 'next.config.ts',
    contents: `import type { NextConfig } from 'next';\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`,
  };
}

function renderGlobalsCss(): OutputFile {
  return {
    path: 'app/globals.css',
    contents: `@import 'tailwindcss';\n@import '@aspect/tokens/css';\n@import '@aspect/css';\n\n@layer base {\n  body {\n    background-color: var(--mizu-surface-default);\n    color: var(--mizu-text-primary);\n    font-family: var(--mizu-font-family-sans);\n  }\n}\n`,
  };
}

function renderRootLayout(plan: Plan): OutputFile {
  const safeTitle = plan.intent.productName.replace(/'/g, "\\'");
  const safeDescription = plan.intent.description.replace(/'/g, "\\'");
  const lines = [
    `import type { Metadata } from 'next';`,
    `import './globals.css';`,
    ``,
    `export const metadata: Metadata = {`,
    `  title: '${safeTitle}',`,
    `  description: '${safeDescription}',`,
    `};`,
    ``,
    `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
    `  return (`,
    `    <html lang="en">`,
    `      <body>{children}</body>`,
    `    </html>`,
    `  );`,
    `}`,
    ``,
  ];
  return {
    path: 'app/layout.tsx',
    contents: lines.join('\n'),
  };
}

function renderIndexPage(plan: Plan): OutputFile | null {
  const hasIndex = plan.entries.some((entry) => entry.route === '/');
  if (hasIndex) return null;
  return {
    path: 'app/page.tsx',
    contents: `export default function HomePage() {\n  return (\n    <main style={{ padding: '2rem' }}>\n      <h1>${plan.intent.productName}</h1>\n      <p>${plan.intent.description}</p>\n    </main>\n  );\n}\n`,
  };
}

function renderGitignore(): OutputFile {
  return {
    path: '.gitignore',
    contents: [
      'node_modules/',
      '.next/',
      'out/',
      'dist/',
      '.DS_Store',
      '.env',
      '.env.local',
      '.env*.local',
      '*.log',
      '',
    ].join('\n'),
  };
}

function renderLicense(): OutputFile {
  const year = new Date().getFullYear();
  return {
    path: 'LICENSE',
    contents: `MIT License\n\nCopyright (c) ${year}\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in\nall copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n`,
  };
}

function dedupeAndSort(files: OutputFile[]): OutputFile[] {
  const map = new Map<string, OutputFile>();
  for (const file of files) {
    map.set(file.path, file);
  }
  return Array.from(map.values()).sort((a, b) => {
    if (a.path < b.path) return -1;
    if (a.path > b.path) return 1;
    return 0;
  });
}

export function buildProjectFiles(plan: Plan): OutputFile[] {
  const patterns = resolvePatternsForPlan(plan);
  const ctx = {
    productName: plan.intent.productName,
    description: plan.intent.description,
  };

  const files: OutputFile[] = [];

  files.push(renderPackageJson(plan));
  files.push(renderReadme(plan));
  files.push(renderSubstrate(plan));
  files.push(renderTsconfig());
  files.push(renderNextConfig());
  files.push(renderGlobalsCss());
  files.push(renderRootLayout(plan));
  files.push(renderGitignore());
  files.push(renderLicense());

  const indexPage = renderIndexPage(plan);
  if (indexPage) files.push(indexPage);

  for (const pattern of patterns) {
    const out = pattern.renderReact(ctx);
    for (const file of out) {
      files.push(file);
    }
  }

  return dedupeAndSort(files);
}

export async function buildProjectZip(plan: Plan): Promise<Blob> {
  const { default: JSZip } = await import('jszip');
  const zip = new JSZip();
  const files = buildProjectFiles(plan);
  for (const file of files) {
    zip.file(file.path, file.contents);
  }
  return zip.generateAsync({ type: 'blob' });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
