'use client';

import { resolvePatternsForPlan, type Plan } from '@/lib/studio/composer';
import { cn } from '@/utils/cn';
import { Badge, Split, Stack } from '@aspect/react';
import { useMemo, useState } from 'react';

export function SharedPlanView({ plan }: { plan: Plan }) {
  const patterns = useMemo(() => resolvePatternsForPlan(plan), [plan]);
  const [active, setActive] = useState(0);
  const entry = plan.entries[active];
  const pattern = patterns[active];
  const Preview = pattern?.Preview;

  return (
    <Stack gap="1.25rem">
      <Stack gap="0.25rem" className="text-muted-foreground text-sm">
        <span>{plan.rationale}</span>
      </Stack>

      <Split fraction="220px 1fr" gap="1.5rem">
        <Stack as="nav" gap="0.25rem" aria-label="Shared pages">
          {plan.entries.map((item, index) => {
            const activePage = index === active;
            const p = patterns[index];
            return (
              <button
                key={`${item.patternId}-${index}`}
                type="button"
                onClick={() => setActive(index)}
                aria-current={activePage ? 'true' : undefined}
                className={cn(
                  'rounded-lg border px-3 py-2 text-left transition-colors',
                  activePage
                    ? 'border-primary bg-primary/5'
                    : 'hover:border-border hover:bg-muted/60 border-transparent',
                )}
              >
                <Stack gap="0.125rem" align="start">
                  <span className="text-foreground text-sm font-semibold">{item.title}</span>
                  <span className="text-muted-foreground text-xs">{item.route}</span>
                  <span className="text-muted-foreground text-[11px]">
                    {p?.meta.name ?? item.patternId}
                  </span>
                </Stack>
              </button>
            );
          })}
        </Stack>
        <section
          aria-label={`Preview of ${entry?.title ?? 'page'}`}
          className="border-border bg-background rounded-lg border p-6"
        >
          {Preview ? <Preview /> : null}
        </section>
      </Split>

      <Stack as="footer" gap="0.25rem" align="start">
        <Badge tone="neutral">Read-only · generated by tweakmizu</Badge>
      </Stack>
    </Stack>
  );
}
