import { defaultStyles } from '@/config/theme';
import { ThemeEditorState } from '@/types/editor';
import { ThemeStyleProps } from '@/types/theme';
import { ColorFormat } from '../types';
import { colorFormatter } from './color-converter';

/** Token keys that are colors (should be formatted) vs raw values (pass through) */
const COLOR_KEYS: (keyof ThemeStyleProps)[] = [
  'action-primary-default',
  'action-primary-hover',
  'action-primary-active',
  'action-primary-disabled',
  'action-destructive-default',
  'action-destructive-hover',
  'action-destructive-active',
  'action-destructive-disabled',
  'feedback-success-default',
  'feedback-success-subtle',
  'feedback-warning-default',
  'feedback-warning-subtle',
  'feedback-danger-default',
  'feedback-danger-subtle',
  'surface-default',
  'surface-secondary',
  'surface-inverse',
  'text-primary',
  'text-secondary',
  'text-inverse',
  'text-disabled',
  'border-default',
  'border-strong',
];

/**
 * Generate a full CSS block with --mizu-* custom properties.
 *
 * @param selector - CSS selector, e.g. `:root` or `[data-mizu-identity="my-theme"]`
 * @param styles - resolved ThemeStyleProps
 * @param colorFormat - output color format
 * @param onlyOverrides - if true, only output values that differ from defaults
 */
function generateCssBlock(
  selector: string,
  styles: ThemeStyleProps,
  colorFormat: ColorFormat,
  onlyOverrides: boolean,
): string {
  const formatColor = (value: string) => colorFormatter(value, colorFormat);
  const lines: string[] = [];

  for (const [key, value] of Object.entries(styles)) {
    if (value === undefined) continue;

    if (onlyOverrides) {
      const defaultVal = defaultStyles[key as keyof ThemeStyleProps];
      if (value === defaultVal) continue;
    }

    const isColor = COLOR_KEYS.includes(key as keyof ThemeStyleProps);
    const formatted = isColor ? formatColor(value) : value;
    lines.push(`  --mizu-${key}: ${formatted};`);
  }

  if (lines.length === 0) return '';
  return `${selector} {\n${lines.join('\n')}\n}`;
}

type OutputScope = 'root' | 'identity';

/**
 * Generate the full exportable CSS output.
 */
export function generateThemeCode(
  state: ThemeEditorState,
  colorFormat: ColorFormat = 'hex',
  scope: string = 'root',
): string {
  const { styles, preset } = state;

  const selector = scope === 'identity' && preset ? `[data-mizu-identity="${preset}"]` : ':root';

  const onlyOverrides = scope === 'identity';
  const block = generateCssBlock(selector, styles, colorFormat, onlyOverrides);

  if (!block) {
    return `/* No overrides — this theme matches the mizu defaults. */`;
  }

  const header = [
    `/*`,
    ` * Generated by tweakmizu`,
    preset ? ` * Based on: ${preset}` : null,
    ` *`,
    ` * Paste this into your project's CSS.`,
    scope === 'identity'
      ? ` * Apply with: <html data-mizu-identity="${preset}">`
      : ` * These variables override the :root defaults.`,
    ` */`,
  ]
    .filter(Boolean)
    .join('\n');

  return `${header}\n\n${block}\n`;
}

/**
 * Stub: generate a Tailwind v3 config snippet (not used in mizu, kept for code-panel compat).
 */
export function generateTailwindConfigCode(
  state: ThemeEditorState,
  _colorFormat: ColorFormat = 'hex',
  _tailwindVersion: string = '4',
): string {
  return `// Tailwind config generation is not supported in tweakmizu.\n// Use the CSS output instead.\n`;
}

/**
 * Stub: generate a layout.tsx snippet (not used in mizu, kept for code-panel compat).
 */
export function generateLayoutCode(_state: ThemeEditorState): string {
  return `// Layout code generation is not supported in tweakmizu.\n`;
}

/**
 * Generate a minimal diff — only the overrides from the preset.
 */
export function generateDiffCode(
  state: ThemeEditorState,
  colorFormat: ColorFormat = 'hex',
): string {
  const { styles, preset } = state;
  const selector = preset ? `[data-mizu-identity="${preset}"]` : ':root';

  return generateCssBlock(selector, styles, colorFormat, true) || '/* No overrides */';
}
