import { ThemePreset } from '@/types/theme';

/**
 * All 26 mizu identity themes, extracted from packages/css/src/themes/*.css.
 *
 * Only --mizu-* CSS custom property overrides are included (component-level
 * structural rules like .mizu-button { border-radius: ... } are skipped).
 *
 * var(--mizu-color-*) references have been resolved to hex values using the
 * base palette so presets work without the full token cascade.
 *
 * Note: some properties (radius-2xl, radius-full, easing-in-out,
 * feedback-success-default, feedback-warning-default, feedback-danger-default,
 * feedback-info-default) are present in CSS themes but not yet in the
 * ThemeStyleProps schema — extend it if you need them.
 *
 * Selector notes:
 *   - Most themes use [data-mizu-identity="<name>"]
 *   - "dark" uses [data-theme="dark"]
 *   - "cloud", "customer-engagement", "ecommerce", "finance" use [data-mizu-theme="<name>"]
 */
export const defaultPresets: Record<string, ThemePreset> = {
  atlas: {
    label: 'Atlas',
    description: 'productivity-focused, token-driven, compact',
    styles: {
      'radius-sm': '0.1875rem',
      'radius-md': '0.25rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.5rem',
      // "radius-2xl": "0.75rem",
      'shadow-sm': '0 1px 1px rgb(9 30 66 / 25%), 0 0 1px 0 rgb(9 30 66 / 31%)',
      'shadow-md': '0 4px 8px -2px rgb(9 30 66 / 25%), 0 0 1px 0 rgb(9 30 66 / 31%)',
      'shadow-lg': '0 8px 16px -4px rgb(9 30 66 / 25%), 0 0 1px 0 rgb(9 30 66 / 31%)',
      'shadow-xl': '0 12px 24px -6px rgb(9 30 66 / 25%), 0 0 1px 0 rgb(9 30 66 / 31%)',
      'font-family-sans':
        '-apple-system, blinkmacsystemfont, "Segoe UI", roboto, "Noto Sans", ubuntu, sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#0c66e4',
      'action-primary-hover': '#05c',
      'action-primary-active': '#09326c',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.15, 1, 0.3, 1)',
    },
  },

  bold: {
    label: 'Bold',
    description: 'high contrast, expressive, brand-forward',
    styles: {
      'radius-sm': '0.375rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.75rem',
      'radius-xl': '1rem',
      'shadow-sm': '0 2px 4px 0 rgb(0 0 0 / 8%)',
      'shadow-md': '0 4px 8px -2px rgb(0 0 0 / 12%)',
      'font-family-sans': '"DM Sans", system-ui, sans-serif',
      'font-weight-medium': '600',
      'font-weight-semibold': '700',
      'font-weight-bold': '800',
      'action-primary-default': '#e11d48',
      'action-primary-hover': '#be123c',
      'action-primary-active': '#9f1239',
      'action-destructive-default': '#dc2626',
      'duration-fast': '120ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
  },

  clinical: {
    label: 'Clinical',
    description: 'accessible-first, high contrast, large touch targets',
    styles: {
      'radius-sm': '0',
      'radius-md': '0.25rem',
      'radius-lg': '0.25rem',
      'radius-xl': '0.25rem',
      // "radius-2xl": "0.25rem",
      'shadow-sm': 'none',
      'shadow-md': 'none',
      'shadow-lg': '0 4px 8px rgb(0 0 0 / 15%)',
      'shadow-xl': '0 8px 16px rgb(0 0 0 / 20%)',
      'font-family-sans': '"Public Sans", "Source Sans Pro", -apple-system, sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '700',
      'font-weight-bold': '700',
      'action-primary-default': '#005ea2',
      'action-primary-hover': '#1a4480',
      'action-primary-active': '#162e51',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
  },

  cloud: {
    label: 'Cloud',
    description: 'Heroku/Railway-flavored: deeper purple primary, slightly cooler grays',
    styles: {
      'action-primary-default': '#6f5ad9',
      'action-primary-hover': '#5b46c2',
      'action-primary-active': '#4a37a6',
      'action-primary-disabled': '#cdc7ed',
    },
  },

  'customer-engagement': {
    label: 'Customer Engagement',
    description: 'friendly, conversational — Intercom vibe',
    styles: {
      'action-primary-default': '#1f8ded',
      'action-primary-hover': '#1576cf',
      'action-primary-active': '#105fa8',
      'action-primary-disabled': '#b8dcf6',
    },
  },

  dark: {
    label: 'Dark',
    description:
      'dark mode override — only overrides semantic tokens that change between light and dark',
    styles: {
      'surface-default': '#020617',
      'surface-secondary': '#0f172a',
      'surface-inverse': '#ffffff',
      'text-primary': '#ffffff',
      'text-secondary': '#94a3b8',
      'text-inverse': '#0f172a',
      'text-disabled': '#475569',
      'border-default': '#1e293b',
      'border-strong': '#475569',
    },
  },

  ecommerce: {
    label: 'Ecommerce',
    description: 'warmer, more saturated — Shopify/Stripe vibe',
    styles: {
      'action-primary-default': '#008060',
      'action-primary-hover': '#006e51',
      'action-primary-active': '#005c44',
      'action-primary-disabled': '#b3d9cf',
    },
  },

  editorial: {
    label: 'Editorial',
    description: 'print-inspired, serif display, content-driven',
    styles: {
      'radius-sm': '0',
      'radius-md': '0.125rem',
      'radius-lg': '0.125rem',
      'radius-xl': '0.25rem',
      // "radius-2xl": "0.25rem",
      'shadow-sm': 'none',
      'shadow-md': 'none',
      'shadow-lg': 'none',
      'shadow-xl': '0 0 0 1px var(--mizu-border-default)',
      'font-family-sans': 'georgia, "Times New Roman", "Noto Serif", serif',
      'font-family-mono': '"Courier Prime", "Courier New", monospace',
      'font-weight-medium': '400',
      'font-weight-semibold': '700',
      'font-weight-bold': '700',
      'action-primary-default': '#121212',
      'action-primary-hover': '#000',
      'action-primary-active': '#000',
      'duration-fast': '0ms',
      'duration-normal': '0ms',
    },
  },

  elevated: {
    label: 'Elevated',
    description: 'material-inspired depth system',
    styles: {
      'radius-sm': '0.25rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.75rem',
      'radius-xl': '1rem',
      'shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 5%), 0 1px 3px 0 rgb(0 0 0 / 10%)',
      'shadow-md': '0 2px 4px -1px rgb(0 0 0 / 6%), 0 4px 6px -1px rgb(0 0 0 / 10%)',
      'shadow-lg': '0 4px 6px -2px rgb(0 0 0 / 5%), 0 10px 15px -3px rgb(0 0 0 / 10%)',
      'shadow-xl': '0 10px 15px -3px rgb(0 0 0 / 10%), 0 20px 25px -5px rgb(0 0 0 / 10%)',
      'font-family-sans': '"Roboto", system-ui, sans-serif',
      'action-primary-default': '#1976d2',
      'action-primary-hover': '#1565c0',
      'action-primary-active': '#0d47a1',
      'duration-fast': '150ms',
      'duration-normal': '300ms',
      'easing-out': 'cubic-bezier(0, 0, 0.2, 1)',
      // "easing-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },

  finance: {
    label: 'Finance',
    description: 'cool, restrained — Mercury/Linear vibe',
    styles: {
      'action-primary-default': '#1e293b',
      'action-primary-hover': '#0f172a',
      'action-primary-active': '#020617',
      'action-primary-disabled': '#cbd5e1',
    },
  },

  fluent: {
    label: 'Fluent',
    description: 'clean, airy, layered depth',
    styles: {
      'radius-sm': '0.125rem',
      'radius-md': '0.25rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.75rem',
      // "radius-2xl": "0.75rem",
      'shadow-sm': '0 2px 4px rgb(0 0 0 / 14%)',
      'shadow-md': '0 4px 8px rgb(0 0 0 / 14%)',
      'shadow-lg': '0 8px 16px rgb(0 0 0 / 14%)',
      'shadow-xl': '0 16px 64px rgb(0 0 0 / 24%)',
      'font-family-sans': '"Segoe UI Variable", "Segoe UI", system-ui, sans-serif',
      'font-weight-medium': '600',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#0078d4',
      'action-primary-hover': '#106ebe',
      'action-primary-active': '#005a9e',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
      // "easing-in-out": "cubic-bezier(0.8, 0, 0.1, 1)",
    },
  },

  industrial: {
    label: 'Industrial',
    description: 'systematic, structured, grid-disciplined',
    styles: {
      'radius-sm': '0',
      'radius-md': '0',
      'radius-lg': '0',
      'radius-xl': '0',
      // "radius-2xl": "0",
      'shadow-sm': 'none',
      'shadow-md': '0 2px 6px rgb(0 0 0 / 20%)',
      'shadow-lg': '0 6px 12px rgb(0 0 0 / 20%)',
      'shadow-xl': '0 12px 24px rgb(0 0 0 / 20%)',
      'font-family-sans': '"IBM Plex Sans", system-ui, sans-serif',
      'font-family-mono': '"IBM Plex Mono", monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#0f62fe',
      'action-primary-hover': '#0353e9',
      'action-primary-active': '#002d9c',
      'duration-fast': '110ms',
      'duration-normal': '240ms',
      'easing-out': 'cubic-bezier(0, 0, 0.38, 0.9)',
      // "easing-in-out": "cubic-bezier(0.2, 0, 0.38, 0.9)",
    },
  },

  layered: {
    label: 'Layered',
    description: 'elevation-heavy, tonal surfaces, expressive motion',
    styles: {
      'radius-sm': '0.25rem',
      'radius-md': '0.75rem',
      'radius-lg': '1rem',
      'radius-xl': '1.25rem',
      // "radius-2xl": "1.75rem",
      // "radius-full": "9999px",
      'shadow-sm': '0 1px 2px rgb(0 0 0 / 15%), 0 1px 3px 1px rgb(0 0 0 / 8%)',
      'shadow-md': '0 1px 2px rgb(0 0 0 / 15%), 0 2px 6px 2px rgb(0 0 0 / 8%)',
      'shadow-lg': '0 4px 8px 3px rgb(0 0 0 / 8%), 0 1px 3px rgb(0 0 0 / 15%)',
      'shadow-xl': '0 6px 10px 4px rgb(0 0 0 / 8%), 0 2px 3px rgb(0 0 0 / 15%)',
      'font-family-sans': '"Google Sans", "Roboto", system-ui, sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '500',
      'font-weight-bold': '700',
      'action-primary-default': '#6750a4',
      'action-primary-hover': '#7e67b8',
      'action-primary-active': '#553f8a',
      'duration-fast': '150ms',
      'duration-normal': '300ms',
      'easing-out': 'cubic-bezier(0.05, 0.7, 0.1, 1)',
      // "easing-in-out": "cubic-bezier(0.2, 0, 0, 1)",
    },
  },

  minimal: {
    label: 'Minimal',
    description: 'stripped back, content-first, documentation-style',
    styles: {
      'radius-sm': '0',
      'radius-md': '0',
      'radius-lg': '0.125rem',
      'radius-xl': '0.25rem',
      'shadow-sm': 'none',
      'shadow-md': 'none',
      'shadow-lg': 'none',
      'shadow-xl': 'none',
      'font-family-sans': '"Source Sans 3", georgia, serif',
      'border-default': '#cbd5e1',
      'action-primary-default': '#0f172a',
      'action-primary-hover': '#1e293b',
      'action-primary-active': '#334155',
      'duration-fast': '0ms',
      'duration-normal': '0ms',
    },
  },

  monochrome: {
    label: 'Monochrome',
    description: 'stark black and white, geometric, developer-tool',
    styles: {
      'radius-sm': '0.3125rem',
      'radius-md': '0.375rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.75rem',
      // "radius-2xl": "0.75rem",
      'shadow-sm': '0 1px 2px rgb(0 0 0 / 4%)',
      'shadow-md': '0 2px 8px rgb(0 0 0 / 8%)',
      'shadow-lg': '0 8px 16px rgb(0 0 0 / 8%)',
      'shadow-xl': '0 16px 48px rgb(0 0 0 / 12%)',
      'font-family-sans': '"Geist", system-ui, sans-serif',
      'font-family-mono': '"Geist Mono", monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'action-primary-default': '#000',
      'action-primary-hover': '#171717',
      'action-primary-active': '#000',
      'duration-fast': '150ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
  },

  muted: {
    label: 'Muted',
    description: 'understated, gray-heavy, developer-focused',
    styles: {
      'radius-sm': '0.25rem',
      'radius-md': '0.375rem',
      'radius-lg': '0.375rem',
      'radius-xl': '0.5rem',
      // "radius-2xl": "0.75rem",
      'shadow-sm': '0 1px 0 rgb(31 35 40 / 4%)',
      'shadow-md': '0 3px 6px rgb(140 149 159 / 15%)',
      'shadow-lg': '0 8px 24px rgb(140 149 159 / 20%)',
      'shadow-xl': '0 12px 28px rgb(140 149 159 / 30%)',
      'font-family-sans':
        '-apple-system, blinkmacsystemfont, "Segoe UI", "Noto Sans", helvetica, arial, sans-serif',
      'font-family-mono': '"SFMono-Regular", consolas, "Liberation Mono", menlo, monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#1f883d',
      'action-primary-hover': '#1a7f37',
      'action-primary-active': '#116329',
      'duration-fast': '80ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.33, 1, 0.68, 1)',
    },
  },

  neon: {
    label: 'Neon',
    description: 'dark-first, vibrant accent, modern dev tools',
    styles: {
      'radius-sm': '0.375rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.75rem',
      'radius-xl': '0.75rem',
      // "radius-2xl": "1rem",
      'shadow-sm': '0 0 4px rgb(0 245 212 / 10%)',
      'shadow-md': '0 0 12px rgb(0 245 212 / 8%)',
      'shadow-lg': '0 0 24px rgb(0 245 212 / 10%)',
      'shadow-xl': '0 0 48px rgb(0 245 212 / 12%)',
      'font-family-sans': '"Inter", system-ui, sans-serif',
      'font-family-mono': '"JetBrains Mono", "Fira Code", monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'action-primary-default': '#00f5d4',
      'action-primary-hover': '#00e5c6',
      'action-primary-active': '#00d4b8',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
  },

  organic: {
    label: 'Organic',
    description: 'warm, content-focused, editorial',
    styles: {
      'radius-sm': '0.1875rem',
      'radius-md': '0.25rem',
      'radius-lg': '0.375rem',
      'radius-xl': '0.5rem',
      // "radius-2xl": "0.5rem",
      'shadow-sm': '0 1px 2px rgb(0 0 0 / 4%)',
      'shadow-md': '0 4px 12px rgb(0 0 0 / 6%)',
      'shadow-lg': '0 8px 24px rgb(0 0 0 / 8%)',
      'shadow-xl': '0 12px 48px rgb(0 0 0 / 10%)',
      'font-family-sans':
        '-apple-system, blinkmacsystemfont, "Segoe UI", helvetica, "Apple Color Emoji", arial, sans-serif',
      'font-family-mono': '"iawriter-mono", "Nitti", menlo, consolas, monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#2f3437',
      'action-primary-hover': '#1e2224',
      'action-primary-active': '#0f1112',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
  },

  playful: {
    label: 'Playful',
    description: 'warm, rounded, friendly, communication-oriented',
    styles: {
      'radius-sm': '0.375rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.75rem',
      'radius-xl': '1rem',
      // "radius-2xl": "1.25rem",
      'shadow-sm': '0 1px 3px rgb(0 0 0 / 8%)',
      'shadow-md': '0 4px 12px rgb(0 0 0 / 10%)',
      'shadow-lg': '0 8px 24px rgb(0 0 0 / 12%)',
      'shadow-xl': '0 16px 48px rgb(0 0 0 / 15%)',
      'font-family-sans': '"Lato", -apple-system, blinkmacsystemfont, "Segoe UI", sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '700',
      'font-weight-bold': '900',
      'action-primary-default': '#611f69',
      'action-primary-hover': '#4a154b',
      'action-primary-active': '#3b1041',
      'duration-fast': '150ms',
      'duration-normal': '250ms',
      'easing-out': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
  },

  precise: {
    label: 'Precise',
    description: 'clean, dark-first, keyboard-centric',
    styles: {
      'radius-sm': '0.25rem',
      'radius-md': '0.375rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.5rem',
      // "radius-2xl": "0.5rem",
      'shadow-sm': '0 1px 2px rgb(0 0 0 / 6%)',
      'shadow-md': '0 2px 8px rgb(0 0 0 / 8%)',
      'shadow-lg': '0 8px 24px rgb(0 0 0 / 16%)',
      'shadow-xl': '0 16px 64px rgb(0 0 0 / 25%)',
      'font-family-sans': '"Inter", system-ui, sans-serif',
      'font-family-mono': '"JetBrains Mono", "Fira Code", monospace',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'action-primary-default': '#5e6ad2',
      'action-primary-hover': '#7c85d8',
      'action-primary-active': '#4e5bc0',
      'duration-fast': '120ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
  },

  refined: {
    label: 'Refined',
    description: 'restrained elegance, generous whitespace',
    styles: {
      'radius-sm': '0.375rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.75rem',
      // "radius-2xl": "0.75rem",
      'shadow-sm': '0 1px 3px rgb(0 0 0 / 8%)',
      'shadow-md': '0 4px 12px rgb(0 0 0 / 8%)',
      'shadow-lg': '0 8px 24px rgb(0 0 0 / 12%)',
      'shadow-xl': '0 12px 48px rgb(0 0 0 / 12%)',
      'font-family-sans':
        '-apple-system, blinkmacsystemfont, "Segoe UI", roboto, "Helvetica Neue", sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'action-primary-default': '#635bff',
      'action-primary-hover': '#7a73ff',
      'action-primary-active': '#5046e5',
      'duration-fast': '150ms',
      'duration-normal': '250ms',
      'easing-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },

  rounded: {
    label: 'Rounded',
    description: 'soft, friendly, consumer-facing',
    styles: {
      'radius-sm': '0.5rem',
      'radius-md': '0.75rem',
      'radius-lg': '1rem',
      'radius-xl': '1.25rem',
      // "radius-2xl": "1.5rem",
      // "radius-full": "9999px",
      'shadow-sm': '0 1px 3px 0 rgb(0 0 0 / 4%)',
      'shadow-md': '0 4px 12px -2px rgb(0 0 0 / 8%)',
      'shadow-lg': '0 12px 24px -4px rgb(0 0 0 / 10%)',
      'shadow-xl': '0 24px 48px -8px rgb(0 0 0 / 12%)',
      'font-family-sans': '"Nunito Sans", system-ui, sans-serif',
      'action-primary-default': '#6366f1',
      'action-primary-hover': '#4f46e5',
      'action-primary-active': '#4338ca',
      'duration-fast': '200ms',
      'duration-normal': '350ms',
      'easing-out': 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },

  sage: {
    label: 'Sage',
    description: 'accounting-grade, slate-tinted neutrals, pill buttons',
    styles: {
      'font-family-sans': '"DM Sans", -apple-system, blinkmacsystemfont, sans-serif',
      'radius-sm': '0.125rem',
      'radius-md': '0.5rem',
      'radius-lg': '0.5rem',
      'radius-xl': '1rem',
      // "radius-2xl": "2rem",
      'shadow-sm': '0 2px 4px 0 rgb(0 20 30 / 15%), 0 3px 3px 0 rgb(0 20 30 / 20%)',
      'shadow-md': '0 5px 5px 0 rgb(0 20 30 / 20%), 0 10px 10px 0 rgb(0 20 30 / 10%)',
      'shadow-lg': '0 10px 20px 0 rgb(0 20 30 / 20%), 0 20px 40px 0 rgb(0 20 30 / 10%)',
      'shadow-xl': '0 10px 30px 0 rgb(0 20 30 / 10%), 0 30px 60px 0 rgb(0 20 30 / 10%)',
      'action-primary-default': '#007e45',
      'action-primary-hover': '#006738',
      'action-primary-active': '#004f2b',
      // "feedback-success-default": "#007e45",
      // "feedback-warning-default": "#ef6700",
      // "feedback-danger-default": "#cb374a",
      // "feedback-info-default": "#0060a7",
      'font-weight-medium': '500',
      'font-weight-semibold': '700',
      'font-weight-bold': '700',
      'text-primary': 'rgb(0 0 0 / 90%)',
      'text-secondary': 'rgb(0 0 0 / 55%)',
      'text-disabled': 'rgb(0 0 0 / 30%)',
      'border-default': '#ccd6db',
      'surface-secondary': '#f2f5f6',
      'duration-fast': '100ms',
      'duration-normal': '150ms',
      'easing-out': 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
  },

  sharp: {
    label: 'Sharp',
    description: 'minimal, editorial, developer-tool',
    styles: {
      'radius-sm': '0.125rem',
      'radius-md': '0.1875rem',
      'radius-lg': '0.25rem',
      'radius-xl': '0.375rem',
      // "radius-2xl": "0.5rem",
      'shadow-sm': 'none',
      'shadow-md': 'none',
      'shadow-lg': 'none',
      'shadow-xl': '0 0 0 1px var(--mizu-border-default)',
      'font-family-sans': '"Geist", system-ui, sans-serif',
      'font-family-mono': '"Geist Mono", "Fira Code", monospace',
      'action-primary-default': '#171717',
      'action-primary-hover': '#0a0a0a',
      'action-primary-active': '#000',
      'duration-fast': '100ms',
      'duration-normal': '150ms',
      'easing-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
  },

  structured: {
    label: 'Structured',
    description: 'dense, utilitarian, productivity-focused',
    styles: {
      'radius-sm': '0.1875rem',
      'radius-md': '0.1875rem',
      'radius-lg': '0.25rem',
      'radius-xl': '0.25rem',
      // "radius-2xl": "0.375rem",
      'shadow-sm': '0 1px 1px rgb(9 30 66 / 25%), 0 0 1px rgb(9 30 66 / 31%)',
      'shadow-md': '0 3px 5px rgb(9 30 66 / 20%), 0 0 1px rgb(9 30 66 / 31%)',
      'shadow-lg': '0 8px 12px rgb(9 30 66 / 15%), 0 0 1px rgb(9 30 66 / 31%)',
      'shadow-xl': '0 12px 24px rgb(9 30 66 / 20%), 0 0 1px rgb(9 30 66 / 31%)',
      'font-family-sans': '-apple-system, blinkmacsystemfont, "Segoe UI", roboto, sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '600',
      'font-weight-bold': '700',
      'action-primary-default': '#0052cc',
      'action-primary-hover': '#0065ff',
      'action-primary-active': '#0747a6',
      'duration-fast': '100ms',
      'duration-normal': '200ms',
      'easing-out': 'cubic-bezier(0.15, 1, 0.3, 1)',
    },
  },

  utilitarian: {
    label: 'Utilitarian',
    description: 'dense, functional, commerce-oriented',
    styles: {
      'radius-sm': '0.1875rem',
      'radius-md': '0.25rem',
      'radius-lg': '0.5rem',
      'radius-xl': '0.5rem',
      // "radius-2xl": "0.5rem",
      'shadow-sm': '0 1px 2px rgb(0 0 0 / 10%)',
      'shadow-md': '0 2px 4px rgb(0 0 0 / 12%)',
      'shadow-lg': '0 4px 8px rgb(0 0 0 / 12%)',
      'shadow-xl': '0 8px 16px rgb(0 0 0 / 15%)',
      'font-family-sans': '"Amazon Ember", "Helvetica Neue", helvetica, arial, sans-serif',
      'font-weight-medium': '500',
      'font-weight-semibold': '700',
      'font-weight-bold': '700',
      'action-primary-default': '#f90',
      'action-primary-hover': '#e88b00',
      'action-primary-active': '#cc7a00',
      'duration-fast': '100ms',
      'duration-normal': '150ms',
      'easing-out': 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
  },
};
