import type { DesignLanguageProfile } from './profile';
import { cssVarsToString, profileToCss, type CssVarMap } from './profile-to-css';

export type ExportFormat =
  | 'json'
  | 'css'
  | 'tailwind'
  | 'html-demo'
  | 'nextjs-starter'
  | 'figma-tokens';

export interface ExportFile {
  path: string;
  content: string;
}

export function exportProfile(
  profile: DesignLanguageProfile,
  formats: ExportFormat[],
): ExportFile[] {
  const files: ExportFile[] = [];
  const vars = profileToCss(profile);

  if (formats.includes('json')) {
    files.push({
      path: 'mizu.language.json',
      content: JSON.stringify(profile, null, 2),
    });
  }

  if (formats.includes('css')) {
    files.push({
      path: 'theme.css',
      content: [
        `/* ${profile.name} — generated by tweakmizu craft */`,
        '',
        cssVarsToString(vars, ':root'),
      ].join('\n'),
    });
  }

  if (formats.includes('tailwind')) {
    files.push({
      path: 'tailwind-theme.css',
      content: generateTailwindBridge(vars, profile.name),
    });
  }

  if (formats.includes('html-demo')) {
    files.push({
      path: 'demo.html',
      content: generateHtmlDemo(profile, vars),
    });
  }

  if (formats.includes('nextjs-starter')) {
    files.push(...generateNextjsStarter(profile, vars));
  }

  if (formats.includes('figma-tokens')) {
    files.push({
      path: 'figma-tokens.json',
      content: generateFigmaTokens(vars, profile.name),
    });
  }

  return files;
}

function generateTailwindBridge(vars: CssVarMap, name: string): string {
  const lines = [
    `/* ${name} — Tailwind v4 @theme bridge generated by tweakmizu craft */`,
    '',
    '@theme {',
  ];
  for (const [key, value] of Object.entries(vars)) {
    const tw = key.replace('--mizu-', '--').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    lines.push(`  ${tw}: ${value};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function generateHtmlDemo(profile: DesignLanguageProfile, vars: CssVarMap): string {
  const cssBlock = cssVarsToString(vars, ':root');
  const name = esc(profile.app?.identity?.productName || profile.name);
  const pages = profile.app?.pages ?? [];
  const firstPage = pages[0];

  const navHtml = (profile.app?.shell?.nav ?? [])
    .map((n) => {
      const p = pages.find((pg) => pg.id === n.pageId);
      return p ? `<a href="#" class="nav-item">${p.title}</a>` : '';
    })
    .filter(Boolean)
    .join('\n        ');

  const kpis = firstPage?.composition.sections
    .filter((s) => s.kind === 'kpi-row')
    .flatMap((s) => s.kpis ?? []);

  const kpiHtml = (kpis ?? [])
    .map(
      (k) => `
        <div class="kpi">
          <div class="kpi-label">${k.label}</div>
          <div class="kpi-value">${k.value}</div>
          ${k.delta ? `<div class="kpi-delta">${k.delta}</div>` : ''}
        </div>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <style>
${cssBlock}

* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: var(--mizu-font-family-sans, system-ui, sans-serif);
  background: var(--mizu-surface-secondary, #f8fafc);
  color: var(--mizu-text-primary, #0f172a);
}
.shell { display: flex; min-height: 100vh; }
.sidebar {
  width: 12rem; padding: 1rem;
  background: var(--mizu-surface-default, #fff);
  border-right: 1px solid var(--mizu-border-subtle, #e2e8f0);
}
.brand { font-weight: 600; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 0.5rem; }
.brand-mark { color: var(--mizu-action-primary-default, #3b82f6); }
.nav-item {
  display: block; padding: 0.5rem 0.75rem;
  border-radius: var(--mizu-radius-md, 6px);
  color: var(--mizu-text-secondary, #64748b);
  text-decoration: none; font-size: 0.875rem;
  margin-bottom: 2px;
}
.nav-item:hover { background: var(--mizu-surface-secondary, #f1f5f9); }
.main { flex: 1; padding: 2rem; max-width: 64rem; }
.page-title { font-size: 1.5rem; font-weight: 700; letter-spacing: -0.015em; }
.page-desc { color: var(--mizu-text-secondary); font-size: 0.875rem; margin-top: 0.25rem; }
.kpis { display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: 1rem; margin-top: 1.5rem; }
.kpi {
  padding: 1rem; background: var(--mizu-surface-default, #fff);
  border: 1px solid var(--mizu-border-subtle, #e2e8f0);
  border-radius: var(--mizu-radius-lg, 8px);
}
.kpi-label { font-size: 0.6875rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--mizu-text-secondary); }
.kpi-value { font-size: 1.375rem; font-weight: 700; margin-top: 0.25rem; font-variant-numeric: tabular-nums; }
.kpi-delta { font-size: 0.75rem; color: var(--mizu-feedback-success-default, #22c55e); margin-top: 0.125rem; }
.btn {
  display: inline-flex; align-items: center; padding: 0.5rem 1rem;
  border-radius: var(--mizu-radius-md, 6px);
  font-size: 0.875rem; font-weight: 500; cursor: pointer; border: 0;
  background: var(--mizu-action-primary-default, #3b82f6); color: #fff;
  margin-top: 1.5rem;
}
.btn:hover { background: var(--mizu-action-primary-hover, #2563eb); }
@media (max-width: 768px) {
  .sidebar { display: none; }
  .main { padding: 1rem; }
}
  </style>
</head>
<body>
  <div class="shell">
    <nav class="sidebar">
      <div class="brand"><span class="brand-mark">${esc(profile.app?.identity?.logo ?? '✷')}</span> ${name}</div>
      ${navHtml}
    </nav>
    <main class="main">
      <h1 class="page-title">${firstPage?.composition.header?.title ?? name}</h1>
      <p class="page-desc">${firstPage?.composition.header?.description ?? ''}</p>
      <div class="kpis">${kpiHtml}</div>
      <button class="btn">${firstPage?.composition.header?.actions[0]?.label ?? 'Get started'}</button>
    </main>
  </div>
</body>
</html>`;
}

function generateNextjsStarter(profile: DesignLanguageProfile, vars: CssVarMap): ExportFile[] {
  const name = profile.app?.identity?.productName || profile.name;
  const slug = name.replace(/\s+/g, '-').toLowerCase();
  const cssBlock = cssVarsToString(vars, ':root');
  const pages = profile.app?.pages ?? [];
  const nav = profile.app?.shell?.nav ?? [];

  const files: ExportFile[] = [];

  files.push({
    path: `${slug}/package.json`,
    content: JSON.stringify(
      {
        name: slug,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          '@aspect/react': 'latest',
          '@aspect/css': 'latest',
        },
        devDependencies: {
          typescript: '^5.0.0',
          '@types/react': '^19.0.0',
          '@types/node': '^22.0.0',
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: `${slug}/tsconfig.json`,
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./src/*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    ),
  });

  files.push({
    path: `${slug}/next.config.ts`,
    content: `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {};

export default nextConfig;
`,
  });

  files.push({
    path: `${slug}/src/app/layout.tsx`,
    content: `import type { Metadata } from 'next';
import '@aspect/css';
import './theme.css';
import './globals.css';

export const metadata: Metadata = {
  title: '${name}',
  description: 'Built with mizu design system',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  });

  files.push({
    path: `${slug}/src/app/theme.css`,
    content: `/* ${name} — generated by tweakmizu craft */\n\n${cssBlock}\n`,
  });

  files.push({
    path: `${slug}/src/app/globals.css`,
    content: `body {
  font-family: var(--mizu-font-family-sans, system-ui, sans-serif);
  background: var(--mizu-surface-secondary);
  color: var(--mizu-text-primary);
  margin: 0;
}
`,
  });

  const navItems = nav
    .map((n) => {
      const page = pages.find((p) => p.id === n.pageId);
      return page ? `  { href: '${page.path}', label: '${page.title}' },` : '';
    })
    .filter(Boolean)
    .join('\n');

  files.push({
    path: `${slug}/src/components/app-shell.tsx`,
    content: `'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import styles from './app-shell.module.css';

const NAV = [
${navItems}
];

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  return (
    <div className={styles.shell}>
      <nav className={styles.sidebar}>
        <div className={styles.brand}>
          <span className={styles.brandMark}>${profile.app?.identity?.logo ?? '✷'}</span>
          <span>${name}</span>
        </div>
        {NAV.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={pathname === item.href ? styles.navItemActive : styles.navItem}
          >
            {item.label}
          </Link>
        ))}
      </nav>
      <main className={styles.main}>{children}</main>
    </div>
  );
}
`,
  });

  files.push({
    path: `${slug}/src/components/app-shell.module.css`,
    content: `.shell { display: flex; min-height: 100dvh; }
.sidebar {
  width: 14rem; padding: 1rem;
  background: var(--mizu-surface-default);
  border-right: 1px solid var(--mizu-border-subtle);
  display: flex; flex-direction: column; gap: 0.125rem;
}
.brand { font-weight: 600; display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1.5rem; }
.brandMark { color: var(--mizu-action-primary-default); font-size: 1.25rem; }
.navItem, .navItemActive {
  display: block; padding: 0.5rem 0.75rem; border-radius: var(--mizu-radius-md);
  font-size: 0.875rem; text-decoration: none; color: var(--mizu-text-secondary);
}
.navItem:hover { background: var(--mizu-surface-secondary); color: var(--mizu-text-primary); }
.navItemActive {
  background: color-mix(in srgb, var(--mizu-action-primary-default) 12%, transparent);
  color: var(--mizu-action-primary-default); font-weight: 500;
}
.main { flex: 1; padding: 2rem; overflow-y: auto; }
`,
  });

  const homePage = pages.find((p) => p.path === '/') ?? pages[0];
  files.push({
    path: `${slug}/src/app/page.tsx`,
    content: `import { AppShell } from '@/components/app-shell';

export default function HomePage() {
  return (
    <AppShell>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 700, letterSpacing: '-0.015em' }}>
        ${homePage?.composition?.header?.title ?? name}
      </h1>
      ${homePage?.composition?.header?.description ? `<p style={{ color: 'var(--mizu-text-secondary)', marginTop: '0.25rem' }}>${homePage.composition.header.description}</p>` : ''}
      <p style={{ marginTop: '2rem', color: 'var(--mizu-text-secondary)' }}>
        Your ${name} app is ready. Start building.
      </p>
    </AppShell>
  );
}
`,
  });

  for (const page of pages) {
    if (page.path === '/') continue;
    const routeDir = page.path.replace(/^\//, '');
    files.push({
      path: `${slug}/src/app/${routeDir}/page.tsx`,
      content: `import { AppShell } from '@/components/app-shell';

export default function ${page.title.replace(/[^a-zA-Z0-9]/g, '').replace(/^[0-9]/, 'P') || 'Page'}Page() {
  return (
    <AppShell>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 700 }}>${page.title}</h1>
      ${page.composition?.header?.description ? `<p style={{ color: 'var(--mizu-text-secondary)' }}>${page.composition.header.description}</p>` : ''}
    </AppShell>
  );
}
`,
    });
  }

  files.push({
    path: `${slug}/mizu.language.json`,
    content: JSON.stringify(profile, null, 2),
  });

  files.push({
    path: `${slug}/README.md`,
    content: `# ${name}

Generated by [tweakmizu craft](https://tweakmizu.vercel.app/craft).

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Design language

This project uses the **${profile.name}** design language built on [mizu](https://github.com/catalysync/mizu).

- \`src/app/theme.css\` — your design tokens as CSS variables
- \`mizu.language.json\` — the full profile (re-import into craft to continue editing)
`,
  });

  return files;
}

/**
 * Generate W3C DTCG (Design Tokens Community Group) JSON compatible with
 * Tokens Studio for Figma. Natively importable by Figma starting Nov 2026.
 */
function generateFigmaTokens(vars: CssVarMap, name: string): string {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tokens: Record<string, any> = {
    $description: `${name} — design tokens generated by tweakmizu craft`,
  };

  for (const [key, value] of Object.entries(vars)) {
    const path = key.replace(/^--mizu-/, '').split('-');

    let type = 'color';
    if (key.includes('spacing') || key.includes('width') || key.includes('size'))
      type = 'dimension';
    if (key.includes('radius')) type = 'dimension';
    if (key.includes('font-family') || key.includes('tracking')) type = 'fontFamily';
    if (key.includes('font-size') || key.includes('base-font')) type = 'dimension';
    if (key.includes('font-weight')) type = 'fontWeight';
    if (key.includes('shadow')) type = 'shadow';
    if (key.includes('duration')) type = 'duration';
    if (key.includes('easing')) type = 'cubicBezier';
    if (
      key.includes('blur') ||
      key.includes('opacity') ||
      key.includes('scale') ||
      key.includes('stroke')
    )
      type = 'number';

    let current = tokens;
    for (let i = 0; i < path.length - 1; i++) {
      if (!current[path[i]]) current[path[i]] = {};
      current = current[path[i]];
    }
    current[path[path.length - 1]] = { $value: value, $type: type };
  }

  return JSON.stringify(tokens, null, 2);
}
