import type { DesignLanguageProfile } from './profile';
import { profileToCss, cssVarsToString, type CssVarMap } from './profile-to-css';

export type ExportFormat = 'json' | 'css' | 'tailwind' | 'html-demo';

export interface ExportFile {
  path: string;
  content: string;
}

export function exportProfile(
  profile: DesignLanguageProfile,
  formats: ExportFormat[],
): ExportFile[] {
  const files: ExportFile[] = [];
  const vars = profileToCss(profile);

  if (formats.includes('json')) {
    files.push({
      path: 'mizu.language.json',
      content: JSON.stringify(profile, null, 2),
    });
  }

  if (formats.includes('css')) {
    files.push({
      path: 'theme.css',
      content: [
        `/* ${profile.name} — generated by tweakmizu craft */`,
        '',
        cssVarsToString(vars, ':root'),
      ].join('\n'),
    });
  }

  if (formats.includes('tailwind')) {
    files.push({
      path: 'tailwind-theme.css',
      content: generateTailwindBridge(vars, profile.name),
    });
  }

  if (formats.includes('html-demo')) {
    files.push({
      path: 'demo.html',
      content: generateHtmlDemo(profile, vars),
    });
  }

  return files;
}

function generateTailwindBridge(vars: CssVarMap, name: string): string {
  const lines = [
    `/* ${name} — Tailwind v4 @theme bridge generated by tweakmizu craft */`,
    '',
    '@theme {',
  ];
  for (const [key, value] of Object.entries(vars)) {
    const tw = key.replace('--mizu-', '--').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    lines.push(`  ${tw}: ${value};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function generateHtmlDemo(profile: DesignLanguageProfile, vars: CssVarMap): string {
  const cssBlock = cssVarsToString(vars, ':root');
  const name = profile.app.identity.productName || profile.name;
  const pages = profile.app.pages;
  const firstPage = pages[0];

  const navHtml = profile.app.shell.nav
    .map((n) => {
      const p = pages.find((pg) => pg.id === n.pageId);
      return p ? `<a href="#" class="nav-item">${p.title}</a>` : '';
    })
    .filter(Boolean)
    .join('\n        ');

  const kpis = firstPage?.composition.sections
    .filter((s) => s.kind === 'kpi-row')
    .flatMap((s) => s.kpis ?? []);

  const kpiHtml = (kpis ?? [])
    .map(
      (k) => `
        <div class="kpi">
          <div class="kpi-label">${k.label}</div>
          <div class="kpi-value">${k.value}</div>
          ${k.delta ? `<div class="kpi-delta">${k.delta}</div>` : ''}
        </div>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <style>
${cssBlock}

* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: var(--mizu-font-family-sans, system-ui, sans-serif);
  background: var(--mizu-surface-secondary, #f8fafc);
  color: var(--mizu-text-primary, #0f172a);
}
.shell { display: flex; min-height: 100vh; }
.sidebar {
  width: 12rem; padding: 1rem;
  background: var(--mizu-surface-default, #fff);
  border-right: 1px solid var(--mizu-border-subtle, #e2e8f0);
}
.brand { font-weight: 600; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 0.5rem; }
.brand-mark { color: var(--mizu-action-primary-default, #3b82f6); }
.nav-item {
  display: block; padding: 0.5rem 0.75rem;
  border-radius: var(--mizu-radius-md, 6px);
  color: var(--mizu-text-secondary, #64748b);
  text-decoration: none; font-size: 0.875rem;
  margin-bottom: 2px;
}
.nav-item:hover { background: var(--mizu-surface-secondary, #f1f5f9); }
.main { flex: 1; padding: 2rem; max-width: 64rem; }
.page-title { font-size: 1.5rem; font-weight: 700; letter-spacing: -0.015em; }
.page-desc { color: var(--mizu-text-secondary); font-size: 0.875rem; margin-top: 0.25rem; }
.kpis { display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: 1rem; margin-top: 1.5rem; }
.kpi {
  padding: 1rem; background: var(--mizu-surface-default, #fff);
  border: 1px solid var(--mizu-border-subtle, #e2e8f0);
  border-radius: var(--mizu-radius-lg, 8px);
}
.kpi-label { font-size: 0.6875rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--mizu-text-secondary); }
.kpi-value { font-size: 1.375rem; font-weight: 700; margin-top: 0.25rem; font-variant-numeric: tabular-nums; }
.kpi-delta { font-size: 0.75rem; color: var(--mizu-feedback-success-default, #22c55e); margin-top: 0.125rem; }
.btn {
  display: inline-flex; align-items: center; padding: 0.5rem 1rem;
  border-radius: var(--mizu-radius-md, 6px);
  font-size: 0.875rem; font-weight: 500; cursor: pointer; border: 0;
  background: var(--mizu-action-primary-default, #3b82f6); color: #fff;
  margin-top: 1.5rem;
}
.btn:hover { background: var(--mizu-action-primary-hover, #2563eb); }
@media (max-width: 768px) {
  .sidebar { display: none; }
  .main { padding: 1rem; }
}
  </style>
</head>
<body>
  <div class="shell">
    <nav class="sidebar">
      <div class="brand"><span class="brand-mark">${profile.app.identity.logo}</span> ${name}</div>
      ${navHtml}
    </nav>
    <main class="main">
      <h1 class="page-title">${firstPage?.composition.header?.title ?? name}</h1>
      <p class="page-desc">${firstPage?.composition.header?.description ?? ''}</p>
      <div class="kpis">${kpiHtml}</div>
      <button class="btn">${firstPage?.composition.header?.actions[0]?.label ?? 'Get started'}</button>
    </main>
  </div>
</body>
</html>`;
}
